### ISSUE TITLE
Future Request: Restore last status after restarting HA.

### ISSUE THREAD

**Issue by LHBL2003** [grimmpp/home-assistant-eltako#63]
After restarting HA, the correct status is not displayed.
Yes, the status could have been changed by a button during the restart. However, the probability is much lower than that everything is supposedly off. It would be good if the status before the restart is restored. It would be good if the status could be restored.

Before restart:
<img width="449" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/eee64477-432b-46e5-ab9b-56ceefcbe3ab">

After restart
<img width="395" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/6bd9efa6-713f-4cf0-a07d-94daeb2de9e5">

**Comment by grimmpp** [comment]
Hello @LHBL2003,

first of all thanks for reporting so many and good feature ideas!!!

I've managed to implement it for sensors like temperature sensors but unfortunately not for binary sensors/switches like lights. I managed HA to remember the latest state and I can read and set it but I'm not able to trigger HA so that it displays its current state. :-(

Unfortunately I also found no docs about it and just checked the HA code. 
That's what I came up with and it seems like self.schedule_update_ha_state() is not working at this point: 
https://github.com/grimmpp/home-assistant-eltako/blob/921e6f840055dfdca3106cacf6eee30a1c90e877/custom_components/eltako/device.py#L149

Here you see values are fitting. I received the latest state and set it to the entity. Looks all perfect: 
![grafik](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/4f63900b-e0d1-49d6-b70e-d850f1421729)
But the WebUI gets reset. 
![grafik](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/b0af4151-4c1f-4c69-ad07-2ec9389fa0ea)

**Comment by grimmpp** [comment]
after hours of searching the bug I almost removed the last piece of code I took over from the beginning. IT WORKS NOW! But now I need time to test it properly. The changes have big potential to break a lot of things.

**Comment by grimmpp** [comment]
Hello @LHBL2003,

state restore feature is implemented and released in v1.3.7. 

Unfortunately, I had to implemented a translation of the generic stored state to the settings of all specific devices. From my understanding HA could have implemented a default translation for every device type. So far I was only able to implement the use cases for the device I own. Actually that should currently cover all supported devices in this integration. 

Let me know if this is good for you to be closed.

**Comment by LHBL2003** [comment]
At first I almost had a heart attack because everything was no longer accessible. But for some reason a lot of entity IDs were created with _2. See picture. But I was able to fix that by deleting the ELTAKO HUB and recreating everything ;)

<img width="1920" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/03fa21d4-8483-4436-99cd-d92bd6842cf3">

But it works really well. After the first start, everything is displayed as Unknown. After the first click, it is defined as OFF. After the second click, the light comes on. It also works great with the blinds.

So it works with FSR14SSR, FSR14-4x, FSB14/12-24V, FSB14

Thank you very much, this enriches the Eltako module soooooooooooooooo much.
