### ISSUE TITLE
Actuators show no status  - ELTAKO ´14 Devices

### ISSUE THREAD

**Issue by FloCodeRian** [grimmpp/home-assistant-eltako#72]
Hi their, 

I´m very happy about this repo because I´m trying to get my setup working for a very long time. 

Unfortunately I´ve experienced a problem with it. 
Within Homeassistant I can't see any status updates of control actuators. Is this behavior normal ?
beside this problem binary sensors are working perfectly.

My setup is eltako only ... fam, fsr, fgw, fud, fstem  
in the moment some of those actuators are controlled with a Homee in parallel. the Homee can see all states of the actuators. 

In homeassistant I see changes are somehow recognized, because every command via home or fst14em - the "last message received" - updates
<img width="770" alt="Automatisierungen" src="https://github.com/grimmpp/home-assistant-eltako/assets/25290446/48740f45-f1d0-4e73-acbe-7ca2c90f9188">

but the FUD´s remain "grey" 
<img width="762" alt="Logbuch" src="https://github.com/grimmpp/home-assistant-eltako/assets/25290446/a9afea98-8dd1-437d-a534-d26bb4b97ccf">

as well as the state of the FSR 14 keeps of , while the light turns on be triggering it with ha
<img width="764" alt="Aus" src="https://github.com/grimmpp/home-assistant-eltako/assets/25290446/8cf93f72-c665-4cab-900a-0a1691f75c48">

i´ll get some "fake" states of the actuators with this text in configuration.yaml
"general_settings:
    fast_status_change: False   # True: Changes status in HA immediately without waiting for actuator response. Default: False"

but that's not what I need

I´d love if someone can help me with any further advices.

**Comment by grimmpp** [comment]
I've tried to reproduce it.
I used a FUD14 (connected via FGW14-USB to HA) and a regular EnOcean Switch from Eltako. 
When dimming by using the wall mounted switch I get e.g.:
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/aa660ea8-634b-4b73-a14f-9ef4e0ab5a71)
and it shows the status correctly in HA, without doing something in HA:
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/e9b6f1dd-34c5-4c1e-916a-bf74969a0c71)
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/4f75a6e2-a5cd-403b-90cf-9dfc978ff713)

The same happens when I choose a dim to e.g. 60%. For a very short moment is is displayed in grey and then it changes to yellow.

On which version did you test. My tests were on v1.3.7.

Could it be that your id of FUD in the configuration is not matching? This would explain wait you see incoming messages but HA entity is not reacting. Sending working independent of it. 
Some people forget that the ids must be defined in hexadecimal. (If your device e.g. has got address 10 in PCT14 then that would result in `00-00-00-0A`) You can also see the id (= address) in the debug logs.

**Comment by FloCodeRian** [comment]
I´m very sorry for the confusion. 

As you expected ... change the ID to the one with a lot of zeros ... like 00-00-00-11 and 00-00-00-13 ... it is working perfect as expected ... 
All my ID´s had like the BASE ID included... because of my old setup with the built-in enocean integration. 
Probably it was because my setup contains an additional FTS14FA. Which I´m actually no sure if I really need it. 

nevertheless - thanks for your support! 

your integration work just perfect :)

**Comment by ureuthe** [comment]
Hi,
even so, the topic is already closed:
In Eltako there are a number of devices (I don't know, if it was 127 or 255) that can send status updates in the bus. Everything with an adress higher than that is not published on the bus.
