### ISSUE TITLE
How to connect the Light Switch

### ISSUE THREAD

**Issue by hesspoint** [grimmpp/home-assistant-eltako#77]
Hi,

I have eltako light switches that uses Enocean PTM215Z.

I managed to connect the switch via Zigbee2MQTT and it shows up in HA via the MQTT integration.

My question is how do I connect the switches to use this custom integration? Is Z2M the right way or is there a better way?

Thanks

**Comment by grimmpp** [comment]
Hello @hesspoint, 

currently the following gateways which can receive the wireless telegrams (also from switches) are: https://github.com/grimmpp/home-assistant-eltako/tree/main/docs/gateways
(USB300 is on the main branch supported but it seems to have some issues regarding sending command telegrams for A5-38-08. In your case should be fine.)
In this sense the switches are actually not really used because the integration watches mainly for state changes of the actuators but switch telegrams are recognized as well and can be used e.g. in Home Assistant automations: https://github.com/grimmpp/home-assistant-eltako/tree/main/docs/rocker_switch

My counter question would be: What do you want to control? If it is an enocean device I would directly program the enocean device to react on the switch. You will receive anyway both signals in the Home Automation Integration. The device representation in HA will be updated independently how you trigger it. When switching e.g. lights on and off by using Home Assistant Integration, the integration anyways should be configured to use independent ids/addresses. This means the physical wall-mounted switch is independent of the virtual HA switch. In any case you can react on the wall-mounted switch events in HA and combine it with any other device. See description above. 
Hint: You can also use button combinations of one switch.

**Comment by grimmpp** [comment]
Sorry, I think I didn't get your question right in the first place. If you don't use any enocean device then this integration most likely makes no sense.
