### ISSUE TITLE
Support for eltako fsb12

### ISSUE THREAD

**Issue by UsefulVid** [grimmpp/home-assistant-eltako#78]
It would be great if Support for eltako fsb12 could be supported.

https://github.com/mak-gitdev/HA_enoceanmqtt/discussions/99

I have a usb300 and ready to do some testing if needed.

**Comment by grimmpp** [comment]
Hello @UsefulVid,

USB300 is now supported in new version 1.4.0. 

Regarding the general integration of series 12 I'm not really sure if that will work because of the prerequisites we need. I can of course add some functionality which could help you. Not sure if that would be enough for a working integration. I will ask the eltako guys what they think if we have the required preconditions. 

For switches I added the possibility to react on switch telegrams. So instead of waiting for an status update telegram of the actuator you can react on a wall-mounted switch. For sending telegram you need to enable under general setting `fast_status_change` otherwise the switch in HA is also waiting for an incoming status update of the actuator. Unfortunately, if you want to use two wall-mounted switches it won't work anymore and if HA is not getting all telegrams you are out of sync until you push the switch again. ...

Just let me know what you think could help you.

**Comment by UsefulVid** [comment]
> Hello @UsefulVid,
> 
> USB300 is now supported in new version 1.4.0.
> 
> Regarding the general integration of series 12 I'm not really sure if that will work because of the prerequisites we need. I can of course add some functionality which could help you. Not sure if that would be enough for a working integration. I will ask the eltako guys what they think if we have the required preconditions.
> 
> For switches I added the possibility to react on switch telegrams. So instead of waiting for an status update telegram of the actuator you can react on a wall-mounted switch. For sending telegram you need to enable under general setting `fast_status_change` otherwise the switch in HA is also waiting for an incoming status update of the actuator. Unfortunately, if you want to use two wall-mounted switches it won't work anymore and if HA is not getting all telegrams you are out of sync until you push the switch again. ...
> 
> Just let me know what you think could help you.

Just wanted to push this topic :) Help would be much appreciated

**Comment by grimmpp** [comment]
Hello @UsefulVid,

Regarding the previous post you've sent is a different integration like this one. 

I've talked to the engineers from Eltako and we don't see a technical possibility to integrate it.

If you are still interested in using this integration you would need to exchange your hardware.
Sorry, for the bad news. Eltako series 12 cannot and won't be supported in this integration. Also because this is a personally created integration and I cannot spend the effort and afford too many different hardware setups.
